import type {
  AdvisePageVm,
  DataManagerPageVm,
  DiagnosePageVm,
  OverviewDashboardVm,
} from '../types/view-models';

export const devSeed: {
  overview: OverviewDashboardVm;
  diagnose: DiagnosePageVm;
  advise: AdvisePageVm;
  dataManager: DataManagerPageVm;
} = {
  overview: {
    lastUpdated: 'April 5, 2026',
    dataQuality: 87,
    kpiData: [
      { label: 'Active Regions', value: '17', trend: 'up', trendValue: '+2 this quarter', accentColor: '#2E6DA4' },
      { label: 'Data Completeness', value: '87%', trend: 'up', trendValue: '+5%', accentColor: '#E8C94F' },
      { label: 'High-Priority Divisions', value: '23', accentColor: '#B8860B' },
      { label: 'Teachers Profiled', value: '45,892', trend: 'up', trendValue: '+3,200', accentColor: '#1B3A5C' },
    ],
    priorityRegions: [
      { region: 'Region XII - SOCCSKSARGEN', score: 8.7, gap: 'Specialization Gap', intervention: 'Inquiry-Based Science', confidence: 'high' },
      { region: 'Region V - Bicol', score: 8.4, gap: 'Remote Access', intervention: 'Blended Delivery', confidence: 'high' },
      { region: 'BARMM', score: 8.2, gap: 'Teacher Coverage', intervention: 'Assessment Training', confidence: 'moderate' },
      { region: 'Region XIII - Caraga', score: 7.9, gap: 'Resource Access', intervention: 'Science Improvisation', confidence: 'high' },
      { region: 'Region VIII - Eastern Visayas', score: 7.6, gap: 'Early Career Support', intervention: 'Teaching Math Problem Solving', confidence: 'moderate' },
    ],
    trainingReachData: [
      { id: 'math', program: 'Math Problem Solving', reach: 8500 },
      { id: 'science', program: 'Science Inquiry', reach: 7200 },
      { id: 'language', program: 'Language Strategies', reach: 6800 },
      { id: 'design', program: 'Design Thinking', reach: 5900 },
      { id: 'assessment', program: 'Assessment', reach: 5200 },
    ],
    specializationData: [
      { id: 'science', name: 'Science', value: 35, color: '#2E6DA4' },
      { id: 'math', name: 'Mathematics', value: 30, color: '#A8C8E8' },
      { id: 'languages', name: 'Languages', value: 20, color: '#E8C94F' },
      { id: 'other', name: 'Other', value: 15, color: '#D8D8D8' },
    ],
    participationTrend: [
      { id: 'jan', month: 'Jan', teachers: 2800 },
      { id: 'feb', month: 'Feb', teachers: 3200 },
      { id: 'mar', month: 'Mar', teachers: 3600 },
      { id: 'apr', month: 'Apr', teachers: 4100 },
    ],
  },
  diagnose: {
    sidebarItems: [
      { id: 'national-overview', label: 'National Overview', active: true },
      { id: 'geographic-drilldown', label: 'Geographic Drilldown', active: false },
      { id: 'score-decomposition', label: 'Score Decomposition', active: false },
      { id: 'data-confidence', label: 'Data Confidence', active: false },
      { id: 'cohort-context', label: 'Cohort Context', active: false },
    ],
    nationalSummary: {
      regionCount: 17,
      teacherPopulation: 428950,
      nationalScore: 7.4,
      averageCoverage: 71,
      averageDataQuality: 84,
      highPriorityRegions: 7,
      lastUpdated: 'April 8, 2026',
    },
    regions: [
      { regionCode: '130000000', regionName: 'NCR', teacherPopulation: 32540, starCoverage: 92, underservedScore: 5.1, dataQuality: 95, topGap: 'Mentoring Load', priority: 'low', confidence: 'high' },
      { regionCode: '010000000', regionName: 'Region I - Ilocos', teacherPopulation: 21410, starCoverage: 78, underservedScore: 6.8, dataQuality: 87, topGap: 'STEM Specialization', priority: 'moderate', confidence: 'high' },
      { regionCode: '020000000', regionName: 'Region II - Cagayan Valley', teacherPopulation: 18340, starCoverage: 74, underservedScore: 7.1, dataQuality: 84, topGap: 'Resource Access', priority: 'moderate', confidence: 'moderate' },
      { regionCode: '140000000', regionName: 'CAR', teacherPopulation: 10290, starCoverage: 68, underservedScore: 7.6, dataQuality: 81, topGap: 'Remote Access', priority: 'high', confidence: 'moderate' },
      { regionCode: '030000000', regionName: 'Region III - Central Luzon', teacherPopulation: 28950, starCoverage: 85, underservedScore: 6.0, dataQuality: 89, topGap: 'Specialization Gap', priority: 'moderate', confidence: 'high' },
      { regionCode: '040000000', regionName: 'Region IV-A - CALABARZON', teacherPopulation: 28450, starCoverage: 72, underservedScore: 6.8, dataQuality: 89, topGap: 'Teacher Specialization Gap', priority: 'high', confidence: 'high' },
      { regionCode: '170000000', regionName: 'MIMAROPA', teacherPopulation: 13560, starCoverage: 65, underservedScore: 7.9, dataQuality: 78, topGap: 'Island Access', priority: 'high', confidence: 'moderate' },
      { regionCode: '050000000', regionName: 'Region V - Bicol', teacherPopulation: 23520, starCoverage: 58, underservedScore: 8.4, dataQuality: 80, topGap: 'Remote Access', priority: 'critical', confidence: 'moderate' },
      { regionCode: '060000000', regionName: 'Region VI - Western Visayas', teacherPopulation: 24890, starCoverage: 75, underservedScore: 6.9, dataQuality: 85, topGap: 'Training Throughput', priority: 'moderate', confidence: 'high' },
      { regionCode: '070000000', regionName: 'Region VII - Central Visayas', teacherPopulation: 26110, starCoverage: 88, underservedScore: 5.8, dataQuality: 90, topGap: 'Technology Access', priority: 'low', confidence: 'high' },
      { regionCode: '080000000', regionName: 'Region VIII - Eastern Visayas', teacherPopulation: 16740, starCoverage: 62, underservedScore: 7.6, dataQuality: 79, topGap: 'Infrastructure Quality', priority: 'high', confidence: 'moderate' },
      { regionCode: '090000000', regionName: 'Region IX - Zamboanga Peninsula', teacherPopulation: 15800, starCoverage: 71, underservedScore: 7.2, dataQuality: 82, topGap: 'Coverage Continuity', priority: 'moderate', confidence: 'moderate' },
      { regionCode: '100000000', regionName: 'Region X - Northern Mindanao', teacherPopulation: 17160, starCoverage: 76, underservedScore: 6.7, dataQuality: 84, topGap: 'Subject Mismatch', priority: 'moderate', confidence: 'high' },
      { regionCode: '110000000', regionName: 'Region XI - Davao', teacherPopulation: 19240, starCoverage: 82, underservedScore: 6.1, dataQuality: 88, topGap: 'Coaching Capacity', priority: 'low', confidence: 'high' },
      { regionCode: '120000000', regionName: 'Region XII - SOCCSKSARGEN', teacherPopulation: 16230, starCoverage: 54, underservedScore: 8.7, dataQuality: 77, topGap: 'Specialization Gap', priority: 'critical', confidence: 'moderate' },
      { regionCode: '160000000', regionName: 'Region XIII - Caraga', teacherPopulation: 12110, starCoverage: 60, underservedScore: 7.9, dataQuality: 78, topGap: 'Resource Access', priority: 'high', confidence: 'moderate' },
      { regionCode: '190000000', regionName: 'BARMM', teacherPopulation: 13610, starCoverage: 48, underservedScore: 8.2, dataQuality: 72, topGap: 'Teacher Coverage', priority: 'critical', confidence: 'low' },
    ],
    regionData: null,
    gapFactors: [],
    divisions: [],
    cohorts: [],
    clusters: [],
    scoreFactors: [],
    dataQuality: [],
  },
  advise: {
    recommendations: [
      {
        id: '1',
        region: 'Region XII - SOCCSKSARGEN',
        score: 8.7,
        gap: 'Specialization Gap',
        interventions: ['Inquiry-Based Science (7E Model)', 'Teaching Mathematics through Problem Solving'],
        status: 'pending',
        confidence: 'high',
        deliveryMethod: 'Blended',
        resourceRequirement: 'Medium',
      },
      {
        id: '2',
        region: 'Region V - Bicol',
        score: 8.4,
        gap: 'Remote Access',
        interventions: ['Assessment for Blended Learning', 'Science & Math Improvisation'],
        status: 'pending',
        confidence: 'high',
        deliveryMethod: 'Alternative',
        resourceRequirement: 'High',
      },
      {
        id: '3',
        region: 'BARMM',
        score: 8.2,
        gap: 'Teacher Coverage',
        interventions: ['Language Strategies', 'Interdisciplinary Contextualization'],
        status: 'pending',
        confidence: 'moderate',
        deliveryMethod: 'Face-to-face',
        resourceRequirement: 'High',
      },
    ],
    interventionPortfolio: [
      'Teaching Mathematics through Problem Solving',
      'Inquiry-Based Science (7E Model)',
      'Interdisciplinary Contextualization',
      'Language Strategies',
      'Design Thinking',
      'Assessment for Blended Learning',
      'Science & Math Improvisation',
    ],
  },
  dataManager: {
    dataSources: [
      {
        name: 'DepEd Teacher Master List Q1 2026',
        type: 'Teacher Records',
        region: 'National',
        records: 428950,
        lastUpdated: 'March 30, 2026',
        completeness: 94,
        status: 'validated',
      },
      {
        name: 'STAR Training Attendance - Region IV-A',
        type: 'Training Data',
        region: 'Calabarzon',
        records: 8240,
        lastUpdated: 'April 2, 2026',
        completeness: 89,
        status: 'validated',
      },
      {
        name: 'School Infrastructure Survey',
        type: 'Infrastructure',
        region: 'Multi-region',
        records: 12450,
        lastUpdated: 'April 1, 2026',
        completeness: 76,
        status: 'pending',
      },
      {
        name: 'Remote Area Classification',
        type: 'Geographic Data',
        region: 'National',
        records: 3280,
        lastUpdated: 'March 15, 2026',
        completeness: 68,
        status: 'flagged',
      },
    ],
    validationIssues: [
      { type: 'Missing required field', count: 142, severity: 'high' },
      { type: 'Duplicate record', count: 38, severity: 'moderate' },
      { type: 'Format mismatch', count: 89, severity: 'moderate' },
      { type: 'Out-of-range value', count: 24, severity: 'high' },
      { type: 'Provenance conflict', count: 12, severity: 'low' },
    ],
    dataQualityByRegion: [
      { region: 'NCR', score: 96, completeness: 98, recency: 'Current' },
      { region: 'Region IV-A', score: 89, completeness: 92, recency: 'Current' },
      { region: 'Region XII', score: 84, completeness: 86, recency: 'Recent' },
      { region: 'BARMM', score: 72, completeness: 74, recency: 'Outdated' },
    ],
  },
};
