import type {
  AdvisePageVm,
  DataManagerPageVm,
  DiagnosePageVm,
  OverviewDashboardVm,
} from '../types/view-models';

export const devSeed: {
  overview: OverviewDashboardVm;
  diagnose: DiagnosePageVm;
  advise: AdvisePageVm;
  dataManager: DataManagerPageVm;
} = {
  overview: {
    lastUpdated: 'April 5, 2026',
    dataQuality: 87,
    kpiData: [
      { label: 'Active Regions', value: '17', trend: 'up', trendValue: '+2 this quarter', accentColor: '#2E6DA4' },
      { label: 'Data Completeness', value: '87%', trend: 'up', trendValue: '+5%', accentColor: '#E8C94F' },
      { label: 'High-Priority Divisions', value: '23', accentColor: '#B8860B' },
      { label: 'Teachers Profiled', value: '45,892', trend: 'up', trendValue: '+3,200', accentColor: '#1B3A5C' },
    ],
    priorityRegions: [
      { region: 'Region XII - SOCCSKSARGEN', score: 8.7, gap: 'Specialization Gap', intervention: 'Inquiry-Based Science', confidence: 'high' },
      { region: 'Region V - Bicol', score: 8.4, gap: 'Remote Access', intervention: 'Blended Delivery', confidence: 'high' },
      { region: 'BARMM', score: 8.2, gap: 'Teacher Coverage', intervention: 'Assessment Training', confidence: 'moderate' },
      { region: 'Region XIII - Caraga', score: 7.9, gap: 'Resource Access', intervention: 'Science Improvisation', confidence: 'high' },
      { region: 'Region VIII - Eastern Visayas', score: 7.6, gap: 'Early Career Support', intervention: 'Teaching Math Problem Solving', confidence: 'moderate' },
    ],
    trainingReachData: [
      { id: 'math', program: 'Math Problem Solving', reach: 8500 },
      { id: 'science', program: 'Science Inquiry', reach: 7200 },
      { id: 'language', program: 'Language Strategies', reach: 6800 },
      { id: 'design', program: 'Design Thinking', reach: 5900 },
      { id: 'assessment', program: 'Assessment', reach: 5200 },
    ],
    specializationData: [
      { id: 'science', name: 'Science', value: 35, color: '#2E6DA4' },
      { id: 'math', name: 'Mathematics', value: 30, color: '#A8C8E8' },
      { id: 'languages', name: 'Languages', value: 20, color: '#E8C94F' },
      { id: 'other', name: 'Other', value: 15, color: '#D8D8D8' },
    ],
    participationTrend: [
      { id: 'jan', month: 'Jan', teachers: 2800 },
      { id: 'feb', month: 'Feb', teachers: 3200 },
      { id: 'mar', month: 'Mar', teachers: 3600 },
      { id: 'apr', month: 'Apr', teachers: 4100 },
    ],
  },
  diagnose: {
    sidebarItems: [
      { id: 'profiler', label: 'Regional Profiler', active: true },
      { id: 'division', label: 'Division View', active: false },
      { id: 'cluster', label: 'School Cluster Map', active: false },
      { id: 'cohort', label: 'Teacher Cohort Segments', active: false },
      { id: 'score', label: 'Underserved Score Builder', active: false },
      { id: 'gap', label: 'Gap Factor Analysis', active: false },
      { id: 'confidence', label: 'Data Confidence Panel', active: false },
    ],
    regionData: {
      name: 'Region IV-A Calabarzon',
      teacherPopulation: 28450,
      starCoverage: 72,
      underservedScore: 6.8,
      dataQuality: 89,
      lastUpdated: 'March 28, 2026',
    },
    gapFactors: [
      { id: 'remote-access', factor: 'Remote/Island Access', contribution: 85, confidence: 'high' },
      { id: 'specialization', factor: 'Teacher Specialization Gap', contribution: 72, confidence: 'high' },
      { id: 'resources', factor: 'Resource Availability', contribution: 68, confidence: 'moderate' },
      { id: 'training', factor: 'Training Infrastructure', contribution: 55, confidence: 'moderate' },
      { id: 'connectivity', factor: 'Connectivity Issues', contribution: 48, confidence: 'high' },
    ],
    divisions: [
      { name: 'Cavite', population: 8200, coverage: 78, gap: 'Specialization', score: 7.2, status: 'high' },
      { name: 'Laguna', population: 7100, coverage: 68, gap: 'Access', score: 7.8, status: 'high' },
      { name: 'Batangas', population: 6800, coverage: 74, gap: 'Resources', score: 6.9, status: 'critical' },
      { name: 'Rizal', population: 4200, coverage: 82, gap: 'Infrastructure', score: 6.2, status: 'moderate' },
      { name: 'Quezon', population: 2150, coverage: 58, gap: 'Remote Access', score: 8.4, status: 'critical' },
    ],
    cohorts: [
      { name: 'Early Career', count: 8420, support: 'High', intervention: 'Foundational Training', confidence: 'high' },
      { name: 'Mid Career', count: 12340, support: 'Moderate', intervention: 'Specialized Upskilling', confidence: 'high' },
      { name: 'Senior', count: 6190, support: 'Low', intervention: 'Leadership Development', confidence: 'moderate' },
      { name: 'Near Retirement', count: 1500, support: 'Low', intervention: 'Mentorship Programs', confidence: 'moderate' },
    ],
    clusters: [
      { name: 'Cluster A - Urban Central', schools: 24, teachers: 892, coverage: 85, priority: 'low' },
      { name: 'Cluster B - Suburban North', schools: 18, teachers: 645, coverage: 72, priority: 'moderate' },
      { name: 'Cluster C - Rural East', schools: 32, teachers: 1204, coverage: 58, priority: 'high' },
      { name: 'Cluster D - Island South', schools: 15, teachers: 423, coverage: 45, priority: 'critical' },
    ],
    scoreFactors: [
      { factor: 'Geographic Remoteness', weight: 25, score: 8.2, impact: 'high' },
      { factor: 'Infrastructure Quality', weight: 20, score: 6.5, impact: 'moderate' },
      { factor: 'Teacher Availability', weight: 20, score: 7.8, impact: 'high' },
      { factor: 'Resource Access', weight: 15, score: 5.9, impact: 'moderate' },
      { factor: 'Training Opportunities', weight: 12, score: 6.2, impact: 'moderate' },
      { factor: 'Technology Access', weight: 8, score: 4.5, impact: 'high' },
    ],
    dataQuality: [
      { source: 'Teacher Registry', completeness: 95, accuracy: 92, timeliness: 88, confidence: 'high' },
      { source: 'School Directory', completeness: 89, accuracy: 87, timeliness: 90, confidence: 'high' },
      { source: 'Training Records', completeness: 78, accuracy: 82, timeliness: 75, confidence: 'moderate' },
      { source: 'Geographic Data', completeness: 72, accuracy: 85, timeliness: 68, confidence: 'moderate' },
      { source: 'Resource Inventory', completeness: 65, accuracy: 70, timeliness: 62, confidence: 'low' },
    ],
  },
  advise: {
    recommendations: [
      {
        id: '1',
        region: 'Region XII - SOCCSKSARGEN',
        score: 8.7,
        gap: 'Specialization Gap',
        interventions: ['Inquiry-Based Science (7E Model)', 'Teaching Mathematics through Problem Solving'],
        status: 'pending',
        confidence: 'high',
        deliveryMethod: 'Blended',
        resourceRequirement: 'Medium',
      },
      {
        id: '2',
        region: 'Region V - Bicol',
        score: 8.4,
        gap: 'Remote Access',
        interventions: ['Assessment for Blended Learning', 'Science & Math Improvisation'],
        status: 'pending',
        confidence: 'high',
        deliveryMethod: 'Alternative',
        resourceRequirement: 'High',
      },
      {
        id: '3',
        region: 'BARMM',
        score: 8.2,
        gap: 'Teacher Coverage',
        interventions: ['Language Strategies', 'Interdisciplinary Contextualization'],
        status: 'pending',
        confidence: 'moderate',
        deliveryMethod: 'Face-to-face',
        resourceRequirement: 'High',
      },
    ],
    interventionPortfolio: [
      'Teaching Mathematics through Problem Solving',
      'Inquiry-Based Science (7E Model)',
      'Interdisciplinary Contextualization',
      'Language Strategies',
      'Design Thinking',
      'Assessment for Blended Learning',
      'Science & Math Improvisation',
    ],
  },
  dataManager: {
    dataSources: [
      {
        name: 'DepEd Teacher Master List Q1 2026',
        type: 'Teacher Records',
        region: 'National',
        records: 428950,
        lastUpdated: 'March 30, 2026',
        completeness: 94,
        status: 'validated',
      },
      {
        name: 'STAR Training Attendance - Region IV-A',
        type: 'Training Data',
        region: 'Calabarzon',
        records: 8240,
        lastUpdated: 'April 2, 2026',
        completeness: 89,
        status: 'validated',
      },
      {
        name: 'School Infrastructure Survey',
        type: 'Infrastructure',
        region: 'Multi-region',
        records: 12450,
        lastUpdated: 'April 1, 2026',
        completeness: 76,
        status: 'pending',
      },
      {
        name: 'Remote Area Classification',
        type: 'Geographic Data',
        region: 'National',
        records: 3280,
        lastUpdated: 'March 15, 2026',
        completeness: 68,
        status: 'flagged',
      },
    ],
    validationIssues: [
      { type: 'Missing required field', count: 142, severity: 'high' },
      { type: 'Duplicate record', count: 38, severity: 'moderate' },
      { type: 'Format mismatch', count: 89, severity: 'moderate' },
      { type: 'Out-of-range value', count: 24, severity: 'high' },
      { type: 'Provenance conflict', count: 12, severity: 'low' },
    ],
    dataQualityByRegion: [
      { region: 'NCR', score: 96, completeness: 98, recency: 'Current' },
      { region: 'Region IV-A', score: 89, completeness: 92, recency: 'Current' },
      { region: 'Region XII', score: 84, completeness: 86, recency: 'Recent' },
      { region: 'BARMM', score: 72, completeness: 74, recency: 'Outdated' },
    ],
  },
};
